package com.pdftools.app

import android.content.Context
import com.pdftools.app.model.PdfTool
import com.pdftools.app.model.ToolCategory
import com.pdftools.app.model.ToolId

/**
 * Central registry of all available PDF tools.
 */
object PdfToolsRepository {

    fun getAllTools(context: Context): List<PdfTool> = listOf(
        PdfTool(
            ToolId.MERGE_PDF,
            R.string.feature_merge_pdf,
            R.string.desc_merge_pdf,
            R.drawable.ic_tool_merge,
            ToolCategory.ORGANIZE
        ),
        PdfTool(
            ToolId.SPLIT_PDF,
            R.string.feature_split_pdf,
            R.string.desc_split_pdf,
            R.drawable.ic_tool_split,
            ToolCategory.ORGANIZE
        ),
        PdfTool(
            ToolId.COMPRESS_PDF,
            R.string.feature_compress_pdf,
            R.string.desc_compress_pdf,
            R.drawable.ic_tool_compress,
            ToolCategory.OPTIMIZE
        ),
        PdfTool(
            ToolId.PDF_TO_WORD,
            R.string.feature_pdf_to_word,
            R.string.desc_pdf_to_word,
            R.drawable.ic_tool_pdf_to_word,
            ToolCategory.CONVERT
        ),
        PdfTool(
            ToolId.PDF_TO_POWERPOINT,
            R.string.feature_pdf_to_ppt,
            R.string.desc_pdf_to_ppt,
            R.drawable.ic_tool_pdf_to_ppt,
            ToolCategory.CONVERT
        ),
        PdfTool(
            ToolId.PDF_TO_EXCEL,
            R.string.feature_pdf_to_excel,
            R.string.desc_pdf_to_excel,
            R.drawable.ic_tool_pdf_to_excel,
            ToolCategory.CONVERT
        ),
        PdfTool(
            ToolId.WORD_TO_PDF,
            R.string.feature_word_to_pdf,
            R.string.desc_word_to_pdf,
            R.drawable.ic_tool_word_to_pdf,
            ToolCategory.CONVERT
        ),
        PdfTool(
            ToolId.POWERPOINT_TO_PDF,
            R.string.feature_ppt_to_pdf,
            R.string.desc_ppt_to_pdf,
            R.drawable.ic_tool_ppt_to_pdf,
            ToolCategory.CONVERT
        ),
        PdfTool(
            ToolId.EXCEL_TO_PDF,
            R.string.feature_excel_to_pdf,
            R.string.desc_excel_to_pdf,
            R.drawable.ic_tool_excel_to_pdf,
            ToolCategory.CONVERT
        ),
        PdfTool(
            ToolId.EDIT_PDF,
            R.string.feature_edit_pdf,
            R.string.desc_edit_pdf,
            R.drawable.ic_tool_edit,
            ToolCategory.EDIT
        ),
        PdfTool(
            ToolId.PDF_TO_JPG,
            R.string.feature_pdf_to_jpg,
            R.string.desc_pdf_to_jpg,
            R.drawable.ic_tool_pdf_to_jpg,
            ToolCategory.CONVERT
        ),
        PdfTool(
            ToolId.JPG_TO_PDF,
            R.string.feature_jpg_to_pdf,
            R.string.desc_jpg_to_pdf,
            R.drawable.ic_tool_jpg_to_pdf,
            ToolCategory.CONVERT
        ),
        PdfTool(
            ToolId.SIGN_PDF,
            R.string.feature_sign_pdf,
            R.string.desc_sign_pdf,
            R.drawable.ic_tool_sign,
            ToolCategory.EDIT
        ),
        PdfTool(
            ToolId.WATERMARK_PDF,
            R.string.feature_watermark_pdf,
            R.string.desc_watermark_pdf,
            R.drawable.ic_tool_watermark,
            ToolCategory.EDIT
        ),
        PdfTool(
            ToolId.ROTATE_PDF,
            R.string.feature_rotate_pdf,
            R.string.desc_rotate_pdf,
            R.drawable.ic_tool_rotate,
            ToolCategory.EDIT
        ),
        PdfTool(
            ToolId.HTML_TO_PDF,
            R.string.feature_html_to_pdf,
            R.string.desc_html_to_pdf,
            R.drawable.ic_tool_html_to_pdf,
            ToolCategory.CONVERT
        ),
        PdfTool(
            ToolId.UNLOCK_PDF,
            R.string.feature_unlock_pdf,
            R.string.desc_unlock_pdf,
            R.drawable.ic_tool_unlock,
            ToolCategory.SECURITY
        ),
        PdfTool(
            ToolId.PROTECT_PDF,
            R.string.feature_protect_pdf,
            R.string.desc_protect_pdf,
            R.drawable.ic_tool_protect,
            ToolCategory.SECURITY
        ),
        PdfTool(
            ToolId.ORGANIZE_PDF,
            R.string.feature_organize_pdf,
            R.string.desc_organize_pdf,
            R.drawable.ic_tool_organize,
            ToolCategory.ORGANIZE
        ),
        PdfTool(
            ToolId.PDF_TO_PDFA,
            R.string.feature_pdf_to_pdfa,
            R.string.desc_pdf_to_pdfa,
            R.drawable.ic_tool_pdfa,
            ToolCategory.CONVERT
        ),
        PdfTool(
            ToolId.REPAIR_PDF,
            R.string.feature_repair_pdf,
            R.string.desc_repair_pdf,
            R.drawable.ic_tool_repair,
            ToolCategory.OPTIMIZE
        ),
        PdfTool(
            ToolId.PAGE_NUMBERS,
            R.string.feature_page_numbers,
            R.string.desc_page_numbers,
            R.drawable.ic_tool_page_numbers,
            ToolCategory.EDIT
        ),
        PdfTool(
            ToolId.SCAN_TO_PDF,
            R.string.feature_scan_to_pdf,
            R.string.desc_scan_to_pdf,
            R.drawable.ic_tool_scan,
            ToolCategory.OTHER
        ),
        PdfTool(
            ToolId.OCR_PDF,
            R.string.feature_ocr_pdf,
            R.string.desc_ocr_pdf,
            R.drawable.ic_tool_ocr,
            ToolCategory.OTHER
        ),
        PdfTool(
            ToolId.COMPARE_PDF,
            R.string.feature_compare_pdf,
            R.string.desc_compare_pdf,
            R.drawable.ic_tool_compare,
            ToolCategory.OTHER
        ),
        PdfTool(
            ToolId.REDACT_PDF,
            R.string.feature_redact_pdf,
            R.string.desc_redact_pdf,
            R.drawable.ic_tool_redact,
            ToolCategory.SECURITY
        ),
        PdfTool(
            ToolId.CROP_PDF,
            R.string.feature_crop_pdf,
            R.string.desc_crop_pdf,
            R.drawable.ic_tool_crop,
            ToolCategory.EDIT
        )
    )
}
